### BEGIN dsdeploy
# Provides:          portainer
# Required-Start:
# Short-Description: Control pannel for Docker & Docker Swarm
# Description:       Add a better description here
# VAR   "FQDN"
# DEPLOY        "simple", "remote"
### END dsdeploy

version: '3.4'

services:
  portainer:
    image: portainer/portainer
    command: '-H "tcp://tasks.agent:9001" --tlsskipverify'
    environment:
      LOGSPOUT: 'ignore'
    ports:
      - ${PUBLIC_PORT}:9000
    networks:
      - proxy
      - portainer_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dataportainer:/data
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.port: 9000
        traefik.frontend.rule: "Host:portainer.192.168.20.218.nip.io,portainer.192.168.20.217.nip.io,portainer.192.168.20.216.nip.io"
        traefik.docker.network: 'proxy'
      placement:
        constraints: [node.role == manager]
    
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
      LOGSPOUT: 'ignore'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - portainer_agent
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]



networks:
  portainer_agent:
    external: true
  proxy:
    external: true


volumes:
  dataportainer:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.20.218,nolock,soft,rw"
      device: ":/srv/nfs/volumes/iperal_portainer/portainer"
