#       Docker Stack to deploy ELK + Logspout
#       Based on .......
#       Updated by: Kenneth Peiruza, kenneth@floss.cat
#       Sun Mar  4 13:15:47 CET 2018
#       V7.5.2: Thu Feb  6 09:10:21 CET 2020
#      cluster.name: 'docker-cluster'
#      bootstrap.memory_lock: 'true'
version: '3.6'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.5.2
    environment:
      ES_JAVA_OPTS: '-Xms768m -Xmx768m'
      discovery.type: 'single-node'
      cluster.name: 'mielastic'
      LOGSPOUT: 'ignore'
    networks:
      - elasticsearch
    volumes:
      - /srv/docker/volumes/logspout-elk/elasticsearch/data:/usr/share/elasticsearch/data
    deploy:
      replicas: 1

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.5.2
    environment:
      LOGSPOUT: 'ignore'
    ports:
      - 5000:5000/udp
      - 1514:1514
      - 1514:1514/udp
    volumes:
      - /srv/docker/volumes/logspout-elk/logstash/config:/usr/share/logstash/pipeline/
    depends_on:
      - elasticsearch
    networks:
      - elasticsearch
      - logstash
    deploy:
      replicas: 1

  logspout:
    image: bekt/logspout-logstash
    environment:
      ROUTE_URIS: 'logstash://logstash:5000'
      LOGSPOUT: 'ignore'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - logstash
    networks:
      - logstash
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 30s

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.5.2
    depends_on:
      - elasticsearch
    networks:
      - elasticsearch
      - proxy
    environment:
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
      LOGSPOUT: 'ignore'
    deploy:
      replicas: 1
      labels:
        traefik.port: 5601
        traefik.frontend.rule: "Host:kibana.192.168.20.218.nip.io,kibana.192.168.20.217.nip.io,kibana.192.168.20.216.nip.io"
        traefik.docker.network: "proxy"

  cerebro:
    image: lmenezes/cerebro
    networks:
      - elasticsearch
      - proxy
    deploy:
      replicas: 1
      labels:
        traefik.port: 9000
        traefik.frontend.rule: "Host:cerebro.192.168.20.218.nip.io,cerebro.192.168.20.217.nip.io,cerebro.192.168.20.216.nip.io"
        traefik.docker.network: "proxy"

networks:
  default:
    driver: 'overlay'
  logstash:
    driver: 'overlay'
  elasticsearch:
    driver: 'overlay'
  proxy:
    external: true

