image:
    registry: docker.io
    repository: errm/cheese
    tag: cheddar
ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - host: cheddar.35.233.90.194.nip.io
        paths:
          - "/"
resources:
    requests:
      cpu: 100m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 50Mi

